/*
🚀 Prisma Setup Guide
    npm install prisma --save-dev
    npm install @prisma/client @prisma/adapter-pg p
  # Edit .env with your database (POSTGRESQL_DATABA
    npx prisma generate
    npx prisma studio
    npx prisma migrate dev --name init

*/

// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from 'prisma/config'
import config from './src/app/config/index'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: config.postgresql_database_url
  }
})
